### ISSUE TITLE
this.quillEditor.getSemanticHTML is not a function Angular 17

### ISSUE THREAD

**Issue by akaco** [KillerCodeMonkey/ngx-quill#1832]
Hi,

Firstly, I want to extend my gratitude for developing and maintaining the ngx-quill library. It's been incredibly helpful for implementing rich text editing features in our Angular projects.

I'm currently working with ngx-quill version ^25.1.2 alongside quill version ^1.3.7. While integrating the editor into my Angular application, I've encountered a persistent issue related to updating the model. The specific error message I receive is:

`this.quillEditor.getSemanticHTML is not a function`

Here's a snippet of my implementation:

```
<quill-editor
    [modules]="editorConfig"
    [sanitize]="true"
    [(ngModel)]="editorContent">
</quill-editor>
<pre>new text: <code>{{ editorContent }}</code></pre>
```

I've thoroughly checked the documentation and sources to ensure I'm using the library correctly, particularly regarding model binding and content sanitization. Despite my efforts, this error seems to persist, hindering the dynamic content updates within the editor.

I've created a minimal reproduction of this issue on StackBlitz to provide a clearer view of the problem:[ [Link to StackBlitz]](https://stackblitz.com/edit/angular-gwtebm-quill-test-n2aj8w?file=package.json)

Could you please guide me on how to resolve this issue or suggest any alternatives if I'm approaching this incorrectly? Any insights or suggestions would be greatly appreciated as I'm keen to utilize ngx-quill to its full potential in our project.

Thank you very much for your time and assistance.

Best regards,
Amirreza

**Comment by KillerCodeMonkey** [comment]
Just check the readme v25 is only ment to use with quill v2 rc 

Am 4. April 2024 05:49:23 MESZ schrieb akaco ***@***.***>:
