### ISSUE TITLE
Error on ng build: "Cannot find name 'require' "

### ISSUE THREAD

**Issue by aqmebrak** [KillerCodeMonkey/ngx-quill#64]
I am having this error when my CI server tries to compile my angular app with AOT.

I have several packages' version way above your package version, do you know if it's related to this ?

![image](https://user-images.githubusercontent.com/5966501/30766078-2e82d25a-9ff3-11e7-9d5d-308ae197dbac.png)

**Comment by patadv** [comment]
Getting the same error as well.

**Comment by KillerCodeMonkey** [comment]
yep, aot builds are not working with >1.4.1 because i remove @types/quill, because they are broken if i try to use them.

So i switched temporarily to requiring quill --> this is not allowed in aot.
use 1.4.0 for now.

I will try to get a good solution.

**Comment by aqmebrak** [comment]
I am now using version 1.4.0 without AOT but it is still telling me the same error

**Comment by KillerCodeMonkey** [comment]
okay. i will try to fix the aot build. i would like to keep @types/quill , but i can not get it working by `import Quill from 'quill';`
like it used to be.

**Comment by KillerCodeMonkey** [comment]
@aqmebrak 1.5.1 released and should fix aot build. could you test it?

**Comment by aqmebrak** [comment]
Yes it is working again, thank you very much ! 😄
