### ISSUE TITLE
Cannot find module 'ngx-quill' issue after updating node version from v10.13.0 to v14.16.1

### ISSUE THREAD

**Issue by manojvictor** [KillerCodeMonkey/ngx-quill#1230]
Getting the following errors after updating node(from 10.13.0 to 14.16.1) and npm(6.14.7 to 6.14.12) versions.
```javascript
src/app/mention/mention.component.ts:4:38 - error TS2307: Cannot find module 'ngx-quill' or its corresponding type declarations.

4 import { QuillEditorComponent } from 'ngx-quill'
                                       ~~~~~~~~~~~
src/app/no-toolbar/no-toolbar.component.ts:3:48 - error TS2307: Cannot find module 'ngx-quill' or its corresponding type declarations.

3 import { ContentChange, SelectionChange } from 'ngx-quill'
                                                 ~~~~~~~~~~~
src/app/reactive-forms/reactive-forms.component.ts:3:53 - error TS2307: Cannot find module 'ngx-quill' or its corresponding type declarations.

3 import { ContentChange, QuillEditorComponent } from 'ngx-quill'
                                                      ~~~~~~~~~~~
src/app/reactive-forms/reactive-forms.component.ts:64:8 - error TS2339: Property 'onContentChanged' does not exist on type 'MatQuill'.

64       .onContentChanged
          ~~~~~~~~~~~~~~~~
src/app/app.module.ts:5:29 - error TS2307: Cannot find module 'ngx-quill' or its corresponding type declarations.

5 import { QuillModule } from 'ngx-quill'
```
All the imports from `ngx-quill` fails.

Have tried doing `npm i ngx-quill` and `npm i quill` but nothing solved the issue.

Tried the same with the [ngx-quill-example](https://github.com/killerCodeMonkey/ngx-quill-example) and got the same issue.

My `package.json`

```javascript
{
  "name": "ngx-quill-example",
  "version": "12.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:deploy": "ng build --prod --base-href ngx-quill-example && gh-pages -d ./dist"
  },
  "license": "MIT",
  "private": false,
  "dependencies": {
    "@angular/animations": "^11.2.11",
    "@angular/cdk": "^11.2.10",
    "@angular/common": "^11.2.11",
    "@angular/compiler": "^11.2.11",
    "@angular/core": "^11.2.11",
    "@angular/forms": "^11.2.11",
    "@angular/localize": "^11.2.11",
    "@angular/material": "^11.2.10",
    "@angular/platform-browser": "^11.2.11",
    "@angular/platform-browser-dynamic": "^11.2.11",
    "@angular/router": "^11.2.11",
    "katex": "^0.13.3",
    "ngx-quill": "^13.3.0",
    "quill": "^1.3.7",
    "quill-emoji": "^0.2.0",
    "quill-mention": "^3.0.3",
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1100.7",
    "@angular/cli": "^11.2.10",
    "@angular/compiler-cli": "^11.2.11",
    "@angular/language-service": "^11.2.11",
    "@types/node": "*",
    "@types/quill": "^1.3.10",
    "gh-pages": "^3.1.0",
    "terser": "^4.8.0",
    "ts-node": "^9.1.1",
    "tslint": "~6.1.2",
    "tslint-eslint-rules": "^5.4.0",
    "typescript": "~4.0.5"
  }
}
```

**Comment by KillerCodeMonkey** [comment]
aaand there i released the src files in v13.3.0 instead of the final build ^^. thanks. try v13.3.1
